//! Render the store into the `docs/STATUS.md` human-readable view: the
//! fixed header (stating the store's source-of-truth nature) followed by
//! the table, sorted by [`crate::model::priority_sorted`].
//!
//! Pure function of the store's contents: called after every mutation
//! (`add-task`, `delete-task`) and at migration time, it always produces
//! the same bytes for the same store, so the view can never drift from
//! what's on disk.

use ctx_core::status_table::render_row;

use crate::model::{priority_sorted, Store};

/// The header block, verbatim up to (and including) the table's own
/// header/separator lines. States that this file is generated and that
/// `docs/status.json` is the source of truth (replaces the previous,
/// misleading claim that this file itself derived from `ctx-context`).
const HEADER: &str = "\
# Status

Generated by `ctx-status` from `docs/status.json` (source of truth); edit \
via `ctx-status add-task`/`delete-task`, never by hand.
Rationale: `docs/DECISIONS.md`.

Sorted by impact (high → low), then difficulty (easy → hard) within each
impact band.

| task | description | impact | difficulty |
|---|---|---|---|";

/// Render the full `docs/STATUS.md` document for `store`.
///
/// Ids are not part of this view — they're an internal handle surfaced
/// only through `ctx-status list`, so the table shape stays the 4-column
/// format shared with `ctx-brief`.
#[must_use]
pub fn render_markdown(store: &Store) -> String {
    let mut out = String::from(HEADER);
    for task in &priority_sorted(store) {
        out.push('\n');
        out.push_str(&render_row(&task.row));
    }
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::render_markdown;
    use crate::model::Task;
    use ctx_core::status_table::Row;

    fn row(task: &str, impact: &str, difficulty: &str) -> Task {
        Task {
            id: 1,
            row: Row {
                task: task.to_owned(),
                description: "d".to_owned(),
                impact: impact.to_owned(),
                difficulty: difficulty.to_owned(),
            },
        }
    }

    #[test]
    fn renders_header_then_sorted_rows() {
        let store = vec![row("a", "low", "easy"), row("b", "high", "easy")];
        let rendered = render_markdown(&store);
        assert!(rendered.starts_with("# Status\n"));
        assert!(rendered.contains("docs/status.json"));
        let b_pos = rendered.find("| b |").expect("row b present");
        let a_pos = rendered.find("| a |").expect("row a present");
        assert!(b_pos < a_pos, "high-impact row must render first");
    }

    #[test]
    fn is_deterministic_for_the_same_store() {
        let store = vec![row("a", "medium", "medium")];
        assert_eq!(render_markdown(&store), render_markdown(&store));
    }

    #[test]
    fn appending_a_row_changes_only_the_new_line() {
        let before = vec![row("a", "high", "easy")];
        let mut after = before.clone();
        after.push(row("b", "low", "hard"));
        let before_rendered = render_markdown(&before);
        let after_rendered = render_markdown(&after);
        assert!(after_rendered.starts_with(before_rendered.trim_end_matches('\n')));
    }
}
