//! Static README content for the `.context` directory.

use ctx_summarize::fs::Fs;

use crate::error::ScanError;

/// Conceptual description of the `.context` directory for human readers.
const README: &str = "\
# .context

This directory is a context tree generated by `ctx-scan`. It mirrors the
source tree alongside it: for each source file `foo/bar.rs` there is a
`.context/foo/bar.rs.ctx` containing a machine-readable summary, and each
directory has a `.context/<dir>/rollup.ctx` summarizing its subtree.

These files are consumed by LLM-based tools to load precise, token-frugal
context about a codebase without reading every source file in full.

Each directory also carries a `hashes.json` (content hashes of its
children); `ctx-scan <dir> --check` diffs them against the source with no
model call, and `ctx-scan <dir> --update` regenerates only what changed.
Scope is defined by `.ctxignore` alone (gitignore syntax; seeded once
from `.gitignore` on first scan, then independent of it); secrets and
binaries are always excluded and cannot be un-ignored. If the tree ever
drifts beyond repair, delete `.context/` and run a full `ctx-scan <dir>`.

Do not edit `.ctx`, `rollup.ctx`, or `hashes.json` files by hand — they
will be overwritten on the next scan.
";

/// The fixed README content for the `.context` directory.
#[must_use]
pub const fn readme_text() -> &'static str {
    README
}

/// Write the README to `.context/README.md` via `fs`.
///
/// # Errors
///
/// [`ScanError::Io`] if the file cannot be written.
pub fn write_readme<F: Fs>(fs: &F) -> Result<(), ScanError> {
    fs.write(".context/README.md", README)
        .map_err(|e| ScanError::Io {
            path: ".context/README.md".to_owned(),
            detail: e.to_string(),
        })
}
