//! Static README content for the `.context` directory.

use ctx_summarize::fs::Fs;

use crate::error::ScanError;

/// Conceptual description of the `.context` directory for human readers.
const README: &str = "\
# .context

This directory is a context tree generated by `ctx-scan`. It mirrors the
source tree alongside it: for each source file `foo/bar.rs` there is a
`.context/foo/bar.rs.ctx` containing a machine-readable summary, and each
directory has a `.context/<dir>/rollup.ctx` summarizing its subtree.

These files are consumed by LLM-based tools to load precise, token-frugal
context about a codebase without reading every source file in full.

Regenerate by running `ctx-scan <dir>` again. Summaries reflect the source
as it existed at generation time; re-run after significant changes.

Do not edit `.ctx` or `rollup.ctx` files by hand — they will be
overwritten on the next scan.
";

/// The fixed README content for the `.context` directory.
#[must_use]
pub const fn readme_text() -> &'static str {
    README
}

/// Write the README to `.context/README.md` via `fs`.
///
/// # Errors
///
/// [`ScanError::Io`] if the file cannot be written.
pub fn write_readme<F: Fs>(fs: &F) -> Result<(), ScanError> {
    fs.write(".context/README.md", README)
        .map_err(|e| ScanError::Io {
            path: ".context/README.md".to_owned(),
            detail: e.to_string(),
        })
}
